apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cnv
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops // namespace of the Argo CD instance
spec: {}